### ISSUE TITLE
Spacing for the dropdown items 

### ISSUE THREAD

**Issue by yajiecao** [wonderflow-bv/design#257]
### Feature description

The gap between dropdown items is a bit wide visually

![Screenshot 2021-12-06 at 17 42 36](https://user-images.githubusercontent.com/83701503/144886218-969074c3-eaef-4a58-a216-a0e47d9f21cf.png)
..

### Describe the solution you'd like

![Screenshot 2021-12-06 at 17 43 46](https://user-images.githubusercontent.com/83701503/144886395-0699412f-71d0-40aa-bb4a-b1f3c0fb4caa.png)

- reduce the spacing between dropdown items from 8px to 0px
- add a 8px margin for the separator 

i use the following as a reference 

![Screenshot 2021-12-06 at 17 31 00](https://user-images.githubusercontent.com/83701503/144886852-1c3d4bc4-060e-475d-a314-3156239ae4bc.png)

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

**Comment by alessio-libardi** [comment]
Hello everyone 👋 

Me & @EmanueleQuerzola spotted a possible enhancement for the dropdown items for this case scenario. Basically when we do not use any `icon` the horizontal `padding` for the `<Dropdown.Item />` should be automatically setted to `0` since we don't want to have a left padding when we don't have the icon.

**Comment by equinusocio** [comment]
Hi Alessio, what you are mentioning is probaly not related to this improvement.

Currently the `Dropdown.Item` has a [`padding?: boolean`](https://design.wonderflow.ai/components/dialogs/dropdown/#dropdownitem) option that removes the padding from the Item. This can't be done automatically since items are not context-aware, they don't know about other items and if they have icons.

Also is important to avoid alignment issues to improve readability, you'll [find more info here](https://design.wonderflow.ai/design/recipes/dropdown/#items-with-icons).

**Comment by alessio-libardi** [comment]
Hi @equinusocio thanks for the fast response! 

Another thing that popped up while using the `<Dropdown.Menu />` is that if we create a condition on our children the component throws an error while using the `Children.map(children, ...` function.

The following will throw an error:
```js
<Dropdown.Menu>
  { condition && <Dropdown.Item />
</Dropdown.Menu>
```
